# Generated by Django 4.2.2 on 2023-06-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finches',
            old_name='breed',
            new_name='species',
        ),
    ]
