# Generated by Django 4.2.2 on 2023-06-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_breed_finches_species'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finches',
            new_name='Finche',
        ),
    ]
