# Generated by Django 4.2.2 on 2023-06-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_finches_finche'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finche',
            new_name='Finch',
        ),
    ]
