# Generated by Django 4.2.2 on 2023-06-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_finche_finch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='age',
            field=models.IntegerField(),
        ),
    ]
